---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.asp=9/16)
library(tidyverse)
library(ggcpesrthemes)

theme_cpesr_setup(authors="Julien Gossa",source="https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-parcoursup/")

spoilerTable <- function(df) {
  cat("\n<details>\n")
  cat("  <summary>Voir les données</summary>\n\n")
  
  print(kableExtra::kable(df, format="pipe"))
  
  cat("\n\n</details>\n")
}

source("psdata.R")
```


## Licences d'informatique

```{r info}
info <- ps %>% 
  filter(str_detect(Filière.de.formation.détaillée,"nformatique") | Filière.de.formation.détaillée == "MP2I") %>%
  group_by(Session,Filière=Filière.de.formation.très.agrégée) %>%
  summarise(
    Capacité = sum(Capacité,na.rm=TRUE),
    Candidatures = sum(Candidatures,na.rm=TRUE),
    Propositions = sum(Propositions,na.rm=TRUE),
    Admissions = sum(Admissions,na.rm=TRUE)
  ) %>%
  pivot_longer(Capacité:Admissions, names_to = "Type", values_to = "Nombre") %>%
  mutate(Type = factor(Type, levels=c("Capacité","Candidatures","Propositions","Admissions"))) %>%
  mutate(Filière = factor(Filière, levels = c("Autre formation","BTS", "DUT_BUT", "Licence", "Licence_Las", "CPGE")))
```

```{r info.total}
info %>% 
  group_by(Session,Type) %>%
  summarise(Nombre=sum(Nombre)) %>%
  ggplot(aes(x=Session,y=Nombre,color=Type, fill=Type, group=Type)) +
  geom_line() +
  geom_point(shape=21,size=4, stroke=2, color="white") +
  expand_limits(y=0) +
  theme_cpesr_cap()
```

```{r info.fil}
info %>% 
  ggplot(aes(x=Session,y=Nombre,color=Type, fill=Type, group=Type)) +
  geom_line() +
  geom_point(shape=21,size=4, stroke=1, color="white") +
  facet_wrap(.~Filière) +
  expand_limits(y=0) +
  theme_cpesr_cap()
```

```{r info.fil.capad}
info %>% 
  filter(Type %in% c("Capacité","Admissions")) %>%
  ggplot(aes(x=Session,y=Nombre,color=Type, fill=Type, group=Type)) +
  geom_line() +
  geom_point(shape=21,size=4, stroke=1, color="white") +
  facet_wrap(.~Filière) +
  expand_limits(y=0) +
  theme_cpesr_cap()
```

```{r info.fil.ad}
info %>% 
  filter(Type %in% c("Admissions")) %>%
  ungroup() %>%
  complete(Filière,Session, fill = list(Nombre=0)) %>% 
  mutate(Filière = fct_rev(Filière)) %>%
  ggplot(aes(x=Session,y=Nombre, fill=Filière, group=Filière)) +
  geom_area(color="white", alpha=0.5,size=0.1) +
  expand_limits(y=0) +
  scale_fill_brewer(palette = "Dark2") +
  theme_cpesr_cap() +
  ylab("Admissions") +
  ggtitle("Parcoursup : admissions en Filières informatique")

```


```{r info.L}
info.all <- bind_rows(
  info %>% 
    filter(Filière %in% c("Licence","DUT_BUT"), Type == "Admissions") %>%
    mutate(Filière = paste(Filière, "Informatique")),
  ps %>% 
    group_by(Session) %>%
    summarise(
      Filière = "Ensemble",
      Type = "Admissions",
      Nombre = sum(Admissions))
) %>%
mutate(Filière = factor(Filière,c("Licence Informatique","DUT_BUT Informatique","Ensemble"))) %>%
group_by(Filière) %>%
mutate(Valeur100 = Nombre / first(Nombre) * 100)

info.all %>%
  ggplot(aes(x=Session,y=Valeur100,group=Filière)) +
    geom_line(aes(color=Filière), size=1) +
    geom_point(aes(fill=Filière), shape=21,size=4,stroke=2,color="white") +
    ylab("Admissions (valeur 100 en 2018)") +
    expand_limits(y=c(90,120)) +
    theme_cpesr_cap() +
    ggtitle("Parcoursup : évolution des admissions en Filières informatique \ncomparées à l'ensemble des admissions")
```






```{r IFSI}
ifsi <- bind_rows(
  ps %>% 
    filter(Filière.de.formation.très.agrégée == "IFSI") %>%
    group_by(Session) %>%
    summarise(
      Filière = "IFSI",
      Nombre = sum(Admissions)),
  ps %>% 
    group_by(Session) %>%
    summarise(
      Filière = "Ensemble",
      Nombre = sum(Admissions))
  ) %>%
  filter(Session > 2018) %>%
  mutate(Session = factor(Session)) %>%
  mutate(Filière = factor(Filière,c("IFSI","Ensemble"))) %>%
  group_by(Filière) %>%
  mutate(Valeur100 = Nombre / first(Nombre) * 100)

ifsi %>%
  ggplot(aes(x=Session,y=Valeur100,group=Filière)) +
    geom_line(aes(color=Filière), size=1) +
    geom_point(aes(fill=Filière), shape=21,size=4,stroke=2,color="white") +
    ylab("Admissions (valeur 100 en 2019)") +
    expand_limits(y=c(90,120)) +
    theme_cpesr_cap() +
    ggtitle("Parcoursup : évolution des admissions en IFSI \ncomparées à l'ensemble des admissions")
```

```{r ifsi2}
ifsi %>%
  filter(Filière == "IFSI") %>%
  ggplot(aes(x=Session,y=Nombre,group=Filière)) +
    geom_line(aes(color=Filière), size=1) +
    geom_point(aes(fill=Filière), shape=21,size=4,stroke=2,color="white") +
    ylab("Admissions") +
    expand_limits(y=c(0,30000)) +
    theme_cpesr_cap() +
    ggtitle("Parcoursup : nombre d'admissions en IFSI")
```


```{r ifsi3}
ps %>% 
  filter(Filière.de.formation.très.agrégée == "IFSI") %>%
  group_by(Session,Filière.de.formation.détaillée) %>%
  summarise(
    Filière = "IFSI",
    Admissions = sum(Admissions),
    Capacité = sum(Capacité),
    Candidatures = sum(Candidatures)) %>%
  pivot_longer(c(Admissions,Capacité,Candidatures), names_to="Type", values_to = "Nombre") %>%
  
  filter(Type != "Candidatures") %>%

  ggplot(aes(x=Session,y=Nombre,group=Type)) +
    geom_line(aes(color=Type), size=1) +
    geom_point(aes(fill=Type), shape=21,size=4,stroke=2,color="white") +
    ylab("Nombre") +
    expand_limits(y=c(0,30000)) +
    theme_cpesr_cap() +
    ggtitle("Parcoursup : nombre de candidatures et d'admissions en IFSI")
```


### Places vacantes

```{r pv}


```


### Discrimibilité 

```{r disc}
ps.mentions <- ps %>%
  filter(Session==2021) %>%
  mutate(
    Admis.Mention_inconnue = Dont.effectif.des.admis.néo.bacheliers.sans.information.sur.la.mention.au.bac,
    Admis.Sans_mention = Dont.effectif.des.admis.néo.bacheliers.sans.mention.au.bac,
    Admis.AB = Dont.effectif.des.admis.néo.bacheliers.avec.mention.Assez.Bien.au.bac,
    Admis.B = Dont.effectif.des.admis.néo.bacheliers.avec.mention.Bien.au.bac,
    Admis.TB = Dont.effectif.des.admis.néo.bacheliers.avec.mention.Très.Bien.au.bac,
    Non_Admis.Mention_inconnue = Admis.Mention_inconnue / X..d.admis.néo.bacheliers.sans.information.sur.la.mention.au.bac * 100,
    Non_Admis.Sans_mention = Admis.Sans_mention / X..d.admis.néo.bacheliers.sans.mention.au.bac * 100,
    Non_Admis.AB = Admis.AB / X..d.admis.néo.bacheliers.avec.mention.Assez.Bien.au.bac * 100,
    Non_Admis.B = Admis.B / X..d.admis.néo.bacheliers.avec.mention.Très.Bien.au.bac * 100,
    Non_Admis.TB = Admis.TB / X..d.admis.néo.bacheliers.avec.mention.Très.Bien.au.bac * 100) %>%
  mutate(across(Admis.Mention_inconnue:Non_Admis.TB,~replace(.x,!is.finite(.x),0)))
```

```{r disc.test, eval=FALSE}
ps.mentions %>%
  mutate(
    test1 = Admis.Mention_inconnue + Admis.Sans_mention + Admis.AB + Admis.B + Admis.TB + Non_Admis.Mention_inconnue + Non_Admis.Sans_mention + Non_Admis.AB + Non_Admis.B + Non_Admis.TB,
    test2 = Candidatures,
    test3 = test1 - test2
  )  
```
